const COLUMNS = [
  {
    title: "Product",
    links: [
      { label: "Live demo", href: "#live-demo" },
      { label: "How it works", href: "#how-it-works" },
      { label: "Pricing", href: "#pricing" },
      { label: "Protocol demo", href: "/x402-demo" },
    ],
  },
  {
    title: "Protocol",
    links: [
      { label: "x402 payment flow", href: "/x402-demo" },
      { label: "Scheme: exact", href: "#how-it-works" },
      { label: "Facilitator", href: "https://facilitator.goplausible.xyz" },
      { label: "Settlement receipts", href: "#live-demo" },
    ],
  },
  {
    title: "Algorand",
    links: [
      { label: "Testnet dispenser", href: "https://bank.testnet.algorand.network" },
      { label: "Pera Wallet", href: "https://perawallet.app" },
      { label: "Testnet explorer", href: "https://testnet.explorer.perawallet.app" },
      { label: "Algod: algonode.cloud", href: "https://algonode.io" },
    ],
  },
  {
    title: "About",
    links: [
      { label: "What PagePay is", href: "#top" },
      { label: "Page counting rules", href: "#pricing" },
      { label: "Payment security", href: "#how-it-works" },
      { label: "Status", href: "#live-demo" },
    ],
  },
];

export function Footer() {
  return (
    <footer className="pp-footer">
      <div className="pp-footer-cols">
        {COLUMNS.map((column) => (
          <div key={column.title}>
            <h3>{column.title}</h3>
            <ul>
              {column.links.map((link) => (
                <li key={link.label}>
                  <a href={link.href}>{link.label}</a>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className="pp-footer-legal">
        <p className="pp-fine" style={{ lineHeight: 1.6 }}>
          PagePay is a demonstration of the x402 payment protocol on Algorand Testnet. Testnet funds
          only — no real-world value is transferred. Pera Wallet signs every payment on your own
          device; PagePay never receives a private key or recovery phrase.
        </p>
        <p className="pp-fine" style={{ lineHeight: 1.6, marginTop: 12 }}>
          Copyright 2026 PagePay. Summaries are generated by a language model and may contain
          errors. Documents are processed for the length of the request only.
        </p>
      </div>
    </footer>
  );
}
