/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiPriceRouteImport } from './routes/api/price'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceRoute = ApiPriceRouteImport.update({
  id: '/api/price',
  path: '/api/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/summarize': typeof ApiSummarizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/summarize': typeof ApiSummarizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/summarize': typeof ApiSummarizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/logs' | '/api/price' | '/api/summarize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/logs' | '/api/price' | '/api/summarize'
  id: '__root__' | '/' | '/api/logs' | '/api/price' | '/api/summarize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiPriceRoute: typeof ApiPriceRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price': {
      id: '/api/price'
      path: '/api/price'
      fullPath: '/api/price'
      preLoaderRoute: typeof ApiPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiPriceRoute: ApiPriceRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
