/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as X402DemoRouteImport } from './routes/x402-demo'
import { Route as ApiGroqRouteImport } from './routes/api/groq'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiPriceRouteImport } from './routes/api/price'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiX402DemoRouteImport } from './routes/api/x402-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const X402DemoRoute = X402DemoRouteImport.update({
  id: '/x402-demo',
  path: '/x402-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroqRoute = ApiGroqRouteImport.update({
  id: '/api/groq',
  path: '/api/groq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceRoute = ApiPriceRouteImport.update({
  id: '/api/price',
  path: '/api/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402DemoRoute = ApiX402DemoRouteImport.update({
  id: '/api/x402-demo',
  path: '/api/x402-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/x402-demo': typeof X402DemoRoute
  '/api/groq': typeof ApiGroqRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/x402-demo': typeof ApiX402DemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/x402-demo': typeof X402DemoRoute
  '/api/groq': typeof ApiGroqRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/x402-demo': typeof ApiX402DemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/x402-demo': typeof X402DemoRoute
  '/api/groq': typeof ApiGroqRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/x402-demo': typeof ApiX402DemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/x402-demo'
    | '/api/groq'
    | '/api/logs'
    | '/api/price'
    | '/api/summarize'
    | '/api/x402-demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/x402-demo'
    | '/api/groq'
    | '/api/logs'
    | '/api/price'
    | '/api/summarize'
    | '/api/x402-demo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/x402-demo'
    | '/api/groq'
    | '/api/logs'
    | '/api/price'
    | '/api/summarize'
    | '/api/x402-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  X402DemoRoute: typeof X402DemoRoute
  ApiGroqRoute: typeof ApiGroqRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiPriceRoute: typeof ApiPriceRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiX402DemoRoute: typeof ApiX402DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x402-demo': {
      id: '/x402-demo'
      path: '/x402-demo'
      fullPath: '/x402-demo'
      preLoaderRoute: typeof X402DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groq': {
      id: '/api/groq'
      path: '/api/groq'
      fullPath: '/api/groq'
      preLoaderRoute: typeof ApiGroqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price': {
      id: '/api/price'
      path: '/api/price'
      fullPath: '/api/price'
      preLoaderRoute: typeof ApiPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402-demo': {
      id: '/api/x402-demo'
      path: '/api/x402-demo'
      fullPath: '/api/x402-demo'
      preLoaderRoute: typeof ApiX402DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  X402DemoRoute: X402DemoRoute,
  ApiGroqRoute: ApiGroqRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiPriceRoute: ApiPriceRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiX402DemoRoute: ApiX402DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
